app:
  # 项目访问域名, 结尾不要加 `/`
  app_host: http://localhost:8878

server:
  # HTTP服务监听的端口
  addr: 8878

log:
  # 日志输出路径
  #path = stdout - 打印到标准输出
  #path = ./Log/test.log
  path: ./Log/test.log

database:
  # 数据库连接信息
  # unix:
  host: localhost
  port: 3306
  charset: utf8
  user: root
  password: 123456
  dbname: test
  max_idle_conns: 100
  max_open_conns: 200
  conn_max_life_time: 500