app:
  # 项目访问域名, 结尾不要加 `/`
  app_host: http://localhost:8878

server:
  # HTTP服务监听的端口
  addr: 8878

log:
  # 日志输出路径
  #path = stdout - 打印到标准输出
  #path = ./log/test.log
  path: ./log/test.log

database:
  # 数据库连接信息
  # unix:
  host: localhost
  port: 3306
  charset: utf8
  user: root
  password: 123456
  dbname: test
  max_idle_conns: 100
  max_open_conns: 200
  conn_max_life_time: 500

redis:
  #模式 哨兵sentinel 集群cluster 单机 standalone
  mode: sentinel
  #Redis哨兵模式
  database: 0        #选择redis的第二个数据库
  password: 123456   #redis密码
  masterName: mymaster #哨兵的名字 #下面是所有哨兵集群节点
  url: 
    - 127.0.0.1:26382
    - 127.0.0.1:26383
    - 127.0.0.1:26384